import {
  Gem,
  LaptopMinimal,
  Layers,
  Lightbulb,
  MessageSquareText,
  Redo,
  RussianRuble,
  SquareUserRound,
  Users,
} from 'lucide-react';

export const navItems = [
  {
    title: 'Тарифы',
    link: '/tariffs',
  },
  {
    title: 'Отзывы клиентов',
    link: '/reviews',
  },
  {
    title: 'Где мне ставить',
    link: '/firm',
  },
  {
    title: 'Обучение',
    link: '/learning',
  },
  {
    title: 'Акции',
    link: '/giveaway',
  },
  {
    title: 'Контакты',
    link: '/contacts',
  },
  {
    title: 'История прогнозов',
    link: '/history',
  },
];

export const stats = [
  {
    month: 'Май 2023',
    income: '+207 000 ₽',
    forecasts: '163',
    passRate: '63%',
    avgCoef: '2.2',
    percentage: '+207%',
  },
  {
    month: 'Июнь 2023',
    income: '+213 850 ₽',
    forecasts: '157',
    passRate: '64%',
    avgCoef: '2.1',
    percentage: '+213%',
  },
  {
    month: 'Июль 2023',
    income: '+284 250 ₽',
    forecasts: '156',
    passRate: '75%',
    avgCoef: '2.2',
    percentage: '+284%',
  },
  {
    month: 'Август 2023',
    income: '+246 650 ₽',
    forecasts: '151',
    passRate: '64%',
    avgCoef: '2.2',
    percentage: '+247%',
  },
  {
    month: 'Май 2023',
    income: '+207 000 ₽',
    forecasts: '163',
    passRate: '63%',
    avgCoef: '2.2',
    percentage: '+207%',
  },
  {
    month: 'Июнь 2023',
    income: '+213 850 ₽',
    forecasts: '157',
    passRate: '64%',
    avgCoef: '2.1',
    percentage: '+213%',
  },
  {
    month: 'Июль 2023',
    income: '+284 250 ₽',
    forecasts: '156',
    passRate: '75%',
    avgCoef: '2.2',
    percentage: '+284%',
  },
  {
    month: 'Август 2023',
    income: '+246 650 ₽',
    forecasts: '151',
    passRate: '64%',
    avgCoef: '2.2',
    percentage: '+247%',
  },
];

export const dashboardMenu = [
  {
    title: 'Обзор',
    link: '/dashboard',
    icon: LaptopMinimal,
  },
  {
    title: 'Потоки',
    link: '/dashboard/streams',
    icon: Layers,
  },
  {
    title: 'Регистрации',
    link: '/dashboard/users',
    icon: Users,
  },
  {
    title: 'Postback',
    link: '/dashboard/postbacks',
    icon: Redo,
  },
  {
    title: 'Выплаты',
    link: '/dashboard/payout',
    icon: Gem,
  },
  {
    title: 'Приведи друга',
    link: '/dashboard/ref',
    icon: SquareUserRound,
  },
  {
    title: 'Уровни отчислений',
    link: '/dashboard/levels',
    icon: RussianRuble,
  },
  {
    title: 'Вопросы и ответы',
    link: '/dashboard/help',
    icon: Lightbulb,
  },
  {
    title: 'Поддержка',
    link: '/dashboard/contacts',
    icon: MessageSquareText,
  },
];

export const statistikaData = [
  {
    date: '2024-11-24',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-23',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-22',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-21',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-20',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-19',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-18',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-17',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-16',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-15',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
  {
    date: '2024-11-14',
    visits: 0,
    registrations: 0,
    activations: 0,
    total: 0,
    start: 0,
    key: 0,
    combo: 0,
    totalCancels: 0,
    keyCancels: 0,
    comboCancels: 0,
    successful: 0,
    rebills: 0,
    declined: 0,
    refunds: 0,
    total2: 0,
  },
];
